### ISSUE TITLE
Automatic get offset pointers

### ISSUE THREAD

**Issue by KarmaMod** [D-R-99/UE4SDKGenerator#1]
Finiding offsets via IDA is really pain, it takes a whole day to disassemble the lib on my crappy computer

Is it possible to get GName and GObject automatically just like the Il2Cppdumper?

**Comment by D-R-99** [comment]
> Finiding offsets via IDA is really pain, it takes a whole day to disassemble the lib on my crappy computer
> 
> Is it possible to get GName and GObject automatically just like the Il2Cppdumper?

It take 30min to 1 hour for me, and u not need to wait for Loading whole binary... U can get All needing offsets in only 5-10 min Load

**Comment by KarmaMod** [comment]
But still, it would be nice if automatic is possible
