### ISSUE TITLE
PUBG Mobile 32Bit

### ISSUE THREAD

**Issue by download4you** [D-R-99/UE4SDKGenerator#7]
Can you provide a solution for PUBGM x86?

Try Test this generator SDK on PUBGM x86

`#if defined(__LP64__)
static uintptr_t GNames_Offset = 0x3CC2FD0;
static uintptr_t GUObjectArray_Offset =  0xA558650;
#else
static uintptr_t GNames_Offset = 0x298580C;
static uintptr_t GUObjectArray_Offset = 0x777FE70;
#endif`

**Comment by download4you** [comment]
Try Test this generator SDK on PUBGM x86

**Comment by D-R-99** [comment]
I not have any 32Bit or x86 Game
I have Only 64Bit ..

But for 32Bit, Try to update Target Dir's All Files Class and Struct Fields By adding or removing Pads(Unknown Field), it will work then ...

**Comment by D-R-99** [comment]
Ex...

class UStruct : public UField
{
public:
	UStruct* SuperField;
	UField* Children;
	int32_t PropertySize;
	int32_t MinAlignment;
	char pad_0x0048[0x28];
};

class UScriptStruct : public UStruct
{
public:
	char pad_0x0088[0x10]; //0x0088
};

Here is pad, size  0x28
This pad size will change in 32Bit(x86)

So change all Pads in EngineClasses.h and other Files also in Target Dir Folder

**Comment by download4you** [comment]
Do you have telegram or discord to contact you?

**Comment by D-R-99** [comment]
> Do you have telegram or discord to contact you?

@Dyno0O07 
Telegram
